#ifndef COMMONLIBRARY_GLOBAL_H
#define COMMONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONLIBRARY_LIBRARY)
#  define COMMONLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONLIBRARY_GLOBAL_H
