#ifndef SERIALPORTLIBRARY_GLOBAL_H
#define SERIALPORTLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALPORTLIBRARY_LIBRARY)
#  define SERIALPORTLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALPORTLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALPORTLIBRARY_GLOBAL_H
