#ifndef PLATFORMGLOBAL_GLOBAL_H
#define PLATFORMGLOBAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLATFORMGLOBAL_LIBRARY)
#  define PLATFORMGLOBALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLATFORMGLOBALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLATFORMGLOBAL_GLOBAL_H
