#ifndef COMMONWIDGETLIBRARY_GLOBAL_H
#define COMMONWIDGETLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QObject>

#if defined(COMMONWIDGETLIBRARY_LIBRARY)
#  define COMMONWIDGETLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONWIDGETLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONWIDGETLIBRARY_GLOBAL_H
