#ifndef CONTROLLERCMD_GLOBAL_H
#define CONTROLLERCMD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERCMD_LIBRARY)
#  define CONTROLLERCMDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLERCMDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERCMD_GLOBAL_H
