#ifndef CONTROLLERSP_GLOBAL_H
#define CONTROLLERSP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERSP_LIBRARY)
#  define CONTROLLERSPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLERSPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERSP_GLOBAL_H
