//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfRoadHost.WcfCenterSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfCenterService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCenterSvcReference.ICenterService")]
    public interface ICenterService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICenterService/UploadInOutImage")]
        void UploadInOutImage(string strLocationID, string strRecordID, byte[] inImage, byte[] outImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetFeeData", ReplyAction="http://tempuri.org/ICenterService/GetFeeDataResponse")]
        System.Text.StringBuilder GetFeeData(string strParkID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICenterService/UploadRecordData2")]
        void UploadRecordData2(System.Data.DataTable table);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICenterService/UploadRecordData")]
        void UploadRecordData(System.Text.StringBuilder builder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetData", ReplyAction="http://tempuri.org/ICenterService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICenterService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ICenterService/GetDataUsingDataContractResponse")]
        WcfRoadHost.WcfCenterSvcReference.CompositeType GetDataUsingDataContract(WcfRoadHost.WcfCenterSvcReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICenterServiceChannel : WcfRoadHost.WcfCenterSvcReference.ICenterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CenterServiceClient : System.ServiceModel.ClientBase<WcfRoadHost.WcfCenterSvcReference.ICenterService>, WcfRoadHost.WcfCenterSvcReference.ICenterService {
        
        public CenterServiceClient() {
        }
        
        public CenterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CenterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CenterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UploadInOutImage(string strLocationID, string strRecordID, byte[] inImage, byte[] outImage) {
            base.Channel.UploadInOutImage(strLocationID, strRecordID, inImage, outImage);
        }
        
        public System.Text.StringBuilder GetFeeData(string strParkID) {
            return base.Channel.GetFeeData(strParkID);
        }
        
        public void UploadRecordData2(System.Data.DataTable table) {
            base.Channel.UploadRecordData2(table);
        }
        
        public void UploadRecordData(System.Text.StringBuilder builder) {
            base.Channel.UploadRecordData(builder);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public WcfRoadHost.WcfCenterSvcReference.CompositeType GetDataUsingDataContract(WcfRoadHost.WcfCenterSvcReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
