#ifndef DATAPROTOCOL_GLOBAL_H
#define DATAPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAPROTOCOL_LIBRARY)
#  define DATAPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAPROTOCOL_GLOBAL_H
