#ifndef CONTROLLERNET_GLOBAL_H
#define CONTROLLERNET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERNET_LIBRARY)
#  define CONTROLLERNETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLERNETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERNET_GLOBAL_H
