#ifndef NETWORKLIBRARY_GLOBAL_H
#define NETWORKLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKLIBRARY_LIBRARY)
#  define NETWORKLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NNETWORKLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKLIBRARY_GLOBAL_H
