#ifndef MANIPULATEINIFILE_GLOBAL_H
#define MANIPULATEINIFILE_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QObject>

#if defined(MANIPULATEINIFILE_LIBRARY)
#  define MANIPULATEINIFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MANIPULATEINIFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MANIPULATEINIFILE_GLOBAL_H
