//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CryptoAPI.rc
//
#define IDC_ENCRYPT_FILE                0
#define IDC_DECRYPT_FILE                1
#define IDC_ENCRYPT_FILE_TO             2
#define IDC_QUICK_VIEW_DECRYPT          2
#define IDC_DECRYPT_FILE_TO             3
#define IDS_PROJNAME                    100
#define IDR_CRYPTO                      101
#define IDR_CRYPTOSHELLEXT              102
#define IDS_ERROR_ENCRYPTFILE_FILEOPENFAILED 512
#define IDS_ERROR_OUTOFMEMORY           513
#define IDS_ERROR_ENCRYPT_READING_SOURCE 514
#define IDS_ERROR_ENCRYPT_ENCRYPTION_FAILED 515
#define IDS_ERROR_ENCRYPT_WRITETODESTINATION_FAILED 516
#define IDS_ERROR_ENCRYPT_COPYDESTINATIONTOSOURCE_FAILED 517
#define IDS_ERROR_ENCRYPT_SIGNHASH_FAILED 518
#define IDS_ERROR_DECRYPTFILE_FILEOPENFAILED 519
#define IDS_ERROR_DECRYPT_READKEYSIZE_FAILED 520
#define IDS_ERROR_DECRYPT_READKEY_FAILED 521
#define IDS_ERROR_DECRYPT_IMPORTPRIVATEKEY_FAILED 522
#define IDS_ERROR_DECRYPT_READING_SOURCE 523
#define IDS_ERROR_DECRYPT_DECRYPTION_FAILED 524
#define IDS_ERROR_DECRYPT_WRITETODESTINATION_FAILED 525
#define IDS_ERROR_DECRYPT_SIGNHASH_FAILED 526
#define IDS_ERROR_DECRYPT_COPYDESTINATIONTOSOURCE_FAILED 527
#define IDS_ERROR_HASHCREATE_FAILED     528
#define IDS_ERROR_DECRYPTFILE_READINGFILEVERSION 529
#define IDS_ERROR_ENCRYPT_WRITEFILEFORMATVERSION 530
#define IDS_ERROR_BSTRFROMVECTOR_FAILED 531
#define IDS_ERROR_INITIALIZATION_FAILED 532
#define IDS_ERROR_IMPORTPRIVATEKEY_FAILED 533
#define IDS_ERROR_DECRYPTSTRING_FAILED  534
#define IDS_ERROR_DIGITALSIGNATURE_ENCRYPT_STRING 535
#define IDS_ERROR_DIGITALSIGNATURE_DECRYPT_STRING 536
#define IDS_ERROR_UNSUPORTED_INMEMORY_ENCRYPTION_VERSION 537
#define IDS_ERROR_INVALID_ARG           538
#define IDS_ERROR_DIGITALSIGNATURE_NOTAVAILABLE 539
#define IDS_ERROR_ENCODEDFILE_FILEOPENFAILED 540
#define IDS_ERROR_ENCODEDFILE_FILEIO    541
#define IDS_ERROR_INITIALIZE_NTE_BAD_FLAGS 542
#define IDS_ERROR_INTIALIZE_CREATE_KEY_CONTAINER_FAILED 543
#define IDS_ERROR_INITIALIZE_NTE_BAD_KEYSET_PARAM 544
#define IDS_ERROR_INITIALIZATION_NTE_BAD_PROV_TYPE 545
#define IDS_ERROR_INITIALIZATION_NTE_BAD_SIGNATURE 546
#define IDS_ERROR_INITIALIZATION_NTE_EXISTS 547
#define IDS_ERROR_INITIALIZATION_NTE_KEYSET_ENTRY_BAD 548
#define IDS_ERROR_INITIALIZATION_NTE_KEYSET_NOT_DEF 549
#define IDS_ERROR_INITIALIZATION_NTE_PROV_DLL_NOT_FOUND 550
#define IDS_ERROR_INITIALIZATION_NTE_PROV_TYPE_ENTRY_BAD 551
#define IDS_ERROR_INITIALIZATION_NTE_PROV_TYPE_NO_MATCH 552
#define IDS_ERROR_INITIALIZATION_NTE_PROV_TYPE_NOT_DEF 553
#define IDS_ERROR_INITIALIZATION_NTE_PROVIDER_DLL_FAIL 554
#define IDS_ERROR_INITIALIZATION_NTE_SIGNATURE_FILE_BAD 555
#define IDS_ERROR_INITIALIZATION_CREATE_NEW_CONTAINER_FAILED 556
#define IDS_ERROR_INITIALIZATION_CREATE_DIGSIGKEYS 557
#define IDS_ERROR_INITIALIZATION_CREATE_ENCRYPTIONKEYS 558
#define IDS_ERROR_DECODED_FILEIO        559
#define IDS_UNKNOWN_ERROR               560
#define IDS_ENCRYPT_MENU_ITEM           561
#define IDS_DECRYPT_MENU_ITEM           562
#define IDS_QUICK_VIEW_DECRYPT_MENU_ITEM 564
#define IDS_ENCRYPT_OBJECT_FLYBY_HELP   565
#define IDS_DECRYPT_OBJECT_FLYBY_HELP   566
#define IDS_ENCRYPT_FILE_TO_MENU_ITEM   567
#define IDS_DECRYPT_FILE_TO_MENU_ITEM   568
#define IDS_ENCRYPT_FILE_TO_FLYBY       569
#define IDS_DECRYPT_FILE_TO_FLYBY       570

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
