#ifndef INICONFIGFILE_GLOBAL_H
#define INICONFIGFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INICONFIGFILE_LIBRARY)
#  define INICONFIGFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define INICONFIGFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INICONFIGFILE_GLOBAL_H
