#ifndef CONTROLLERCOMMON_GLOBAL_H
#define CONTROLLERCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERCOMMON_LIBRARY)
#  define CONTROLLERCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLERCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERCOMMON_GLOBAL_H
