#ifndef VEHICLELICENSE_GLOBAL_H
#define VEHICLELICENSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VEHICLELICENSE_LIBRARY)
#  define VEHICLELICENSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VEHICLELICENSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VEHICLELICENSE_GLOBAL_H
