#ifndef MULTIMEDIA_GLOBAL_H
#define MULTIMEDIA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIMEDIA_LIBRARY)
#  define MULTIMEDIASHARED_EXPORT Q_DECL_EXPORT
#else
#  define MULTIMEDIASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIMEDIA_GLOBAL_H
